service: chatgpt-whatsapp-bot

provider:
    name: aws
    runtime: nodejs18.x
    lambdaHashingVersion: 20201221
    memorySize: 1024
    timeout: 1
    environment:
        LOG_LEVEL: info

functions:
    whatsappWebhook:
        handler: src/handler.whatsappWebhookHandler
        url: true

plugins:
    - serverless-plugin-typescript

resources: